name: Build

on:
  workflow_dispatch:
  
  push:
    branches:
    - main
    - release/*

  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.5.0

      - name: Install dependencies
        run: |
          yarn install
          npm install -g gatsby-cli

      - name: Build
        run: yarn build
        env:
          CONTENT_REPO: https://github.com/SSWConsulting/SSW.Website.Content
          CONTENT_BRANCH: main
