# This is a basic workflow to help you get started with Actions
name: Production - Deploy Gatsby Site

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-to-production:
    uses: SSWConsulting/SSW.Website/.github/workflows/build-and-deploy-gatsby.yml@main
    with:
      ENVIRONMENT: Production
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
      CONTENT_BRANCH: ${{ secrets.CONTENT_BRANCH }}
